# Generated by Django 6.0.4 on 2026-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('listing', 'Listing'), ('booking', 'Booking'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, max_length=20),
        ),
    ]
