# Generated by Django 6.0.4 on 2026-05-07 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_agency_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='properties/default.jpg', upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
    ]
