# Generated by Django 6.0.4 on 2026-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_amenity_remove_property_lat_remove_property_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('rented', 'Rented')], default='available', max_length=20),
        ),
    ]
